### ISSUE TITLE
clean way to write apps not working in django 1.7

### ISSUE THREAD

**Issue by redskins80** [marcofucci/cookiecutter-simple-django#8]
RuntimeError: Conflicting 'tag' models in application 'inventory': <class 'inventory.models.Tag'> and <class 'groot.apps.inventory.models.Tag'>.

feels similar to this: https://code.djangoproject.com/ticket/22280#comment:13

here is my sys.path:

    ['/home/redskins80/project-groot/groot/groot/apps',
     '/home/redskins80/project-groot/groot',
     '/home/redskins80/project-groot/env-groot/lib/python2.7',
     '/home/redskins80/project-groot/env-groot/lib/python2.7/plat-x86_64-linux-gnu',
     '/home/redskins80/project-groot/env-groot/lib/python2.7/lib-tk',
     '/home/redskins80/project-groot/env-groot/lib/python2.7/lib-old',
     '/home/redskins80/project-groot/env-groot/lib/python2.7/lib-dynload',
     '/usr/lib/python2.7',
     '/usr/lib/python2.7/plat-x86_64-linux-gnu',
     '/usr/lib/python2.7/lib-tk',
     '/home/redskins80/project-groot/env-groot/local/lib/python2.7/site-packages',
     '/home/redskins80/project-groot/groot',
     '/home/redskins80/project-groot/groot']

is there a way to still structure our apps this way in 1.7?

**Comment by marcofucci** [comment]
I've never had any of these problems, maybe check that you are importing all your modules using relative paths. Also, never use the string `apps` when importing if you're using absolute path, you can just ignore that part as it's in your sys.path anyway.
